Deploy saver
fluidefi/fluidefi-caspernet-aggregator-tools pull request #46
Opened 2022-12-08 09:05 UTC by DevAseel

**Summary of change:**
- Added a new micro-service, deploy saver, which takes a parsed deploy and save it in the datasource. 
- 
**List of tasks:** 
- [x] Define types.
- [x] Define interfaces.
- [x] Define class.
- [x] Create fixture.
- [x] Create mock datasource. 
- [x] Create unit test.
- [x] Generate the docs. 
- [x] Update the documentation.

**Steps for testing**
- Make sure your local git is up to date
```bash
git pull
```

- Checkout the branch `feature/deploy-saver`
```bash
git checkout feature/deploy-saver
```

- Run the test across the test-net
```bash
npm run test
```

- Confirm deploy-saver test has passed.
- Run the docs using live server and make sure it have been updated.

2022-12-08 16:02 UTC, jjfluid commented
> 
>     * Run the test across the test-net
> 

The tests only worked on mainnet for me.

2022-12-08 16:07 UTC, DevAseel commented
> > ```
> > * Run the test across the test-net
> > ```
> 
> The tests only worked on mainnet for me.

@jjfluid I'm assuming you mean the deploy fetcher integration test, for that we need to find some samples that exist in both test-net and main-net. 

```js
const validTestCases: string[] = [
      '57a2fc930ab83f6bf5b3f1d7d5d1bd05ccd20dcbe3135f7c21a0553650d220e6',
      '2ed45dff7b6ca5fde781fd79ae9cb4c68c69c63ac4898d205f937ac05cd4e387',
      'da890a18935ddf8c27760add34bde7c2479b96cb3282d95935b1652167b01abf',
    ];
```

I included test samples from the main-net to pass the test.

2022-12-08 16:08 UTC, jjfluid requested changes

2022-12-08 16:08 UTC, jjfluid commented on src/entities/Deploy.ts
> +  @Column({ name: 'session', type: 'jsonb' })
remove this (session) - will contain the huge moduleBytes hex field, which we dont want in our data store

2022-12-08 16:08 UTC, jjfluid commented on src/services/parsers/DeployParser.ts
> +        session: deploy.fields.deploy.session,
remove this...too big of a field, with data we don't need

2022-12-08 16:10 UTC, jjfluid commented
> 

That's right. It was the DeployFetcher int. tests, on this branch.

2022-12-08 16:12 UTC, DevAseel commented
> Everything else looks good. Nice work

Thanks, will include the changes [here](https://github.com/fluidefi/fluidefi-caspernet-aggregator-tools/pull/47) if you don't mind, just to avoid conflicts. 

> > 
> 
> That's right. It was the DeployFetcher int. tests, on this branch.

For that we need to find a deploy hash that exists in main-net & test-net.

2022-12-08 16:16 UTC, jjfluid commented
> 
> Thanks, will include the changes [here](https://github.com/fluidefi/fluidefi-caspernet-aggregator-tools/pull/47) if you don't mind, just to avoid conflicts.
> 

Yeah sounds good

2022-12-11 19:00 UTC, DevAseel commented
@specialistvlad this one should be closed without merging, all changes are included in #[47](https://github.com/fluidefi/fluidefi-caspernet-aggregator-tools/pull/47).

2022-12-12 14:23 UTC, specialistvlad commented
@DevAseel ok

2022-12-12 14:23 UTC, closed without merging